CREATE schema sistema

CREATE TABLE sistema."PessoaTipo" (
	"IdPessoaTipo" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Nome" varchar(50) NOT NULL,
	"Descricao" varchar(255) NULL,
	"CreatedAt" timestamp NOT NULL,
	"UpdatedAt" timestamp NOT NULL,
	CONSTRAINT "PK_PessoaTipo" PRIMARY KEY ("IdPessoaTipo")
);

CREATE UNIQUE INDEX "IX_PessoaTipo_Nome" ON sistema."PessoaTipo" USING btree ("Nome");

CREATE TABLE sistema."DocumentoTipo" (
	"IdDocumentoTipo" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Nome" varchar(50) NOT NULL,
	"Descricao" varchar(255) NULL,
	"CreatedAt" timestamp NOT NULL,
	"UpdatedAt" timestamp NOT NULL,
	CONSTRAINT "PK_DocumentoTipo" PRIMARY KEY ("IdDocumentoTipo")
);

CREATE UNIQUE INDEX "IX_DocumentoTipo_Nome" ON sistema."DocumentoTipo" USING btree ("Nome");

create schema seguranca